Repository wecode-bootcamp-korea/11-KiBon-frontend, pull requests merged in 2020-08, with the labels that each got.

#1 Modify: reset.scss, common.scss 내용 추가
  src/Pages/Main/Main.js
  src/Pages/Menu/Menu.js
  src/Pages/Menu/Menu.scss
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: enhancement

#6 [이효정] Refactor: 멘토 리뷰 반영
  public/Images/bg_join_auth.png
  src/Pages/SignUp/Agree.js
  src/Pages/SignUp/Agree.scss
  src/Pages/SignUp/Complete.js
  src/Pages/SignUp/Complete.scss
  src/Pages/SignUp/Component/JoinLoginData.js
  src/Pages/SignUp/Component/JoinOderData.js
  src/Pages/SignUp/Component/JoinSelectData.js
  src/Pages/SignUp/Component/JoinTable.js
  src/Pages/SignUp/Component/JoinTable.scss
  src/Pages/SignUp/Component/JoinUserData.js
  src/Pages/SignUp/Component/Joinbox.js
  src/Pages/SignUp/Component/Joinbox.scss
  src/Pages/SignUp/Component/RulBox.js
  src/Pages/SignUp/Component/RulBox.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/Utils.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [이효정]Refactoy: 멘토 리뷰 반영 완료
  src/Pages/Login/MemberForm.js
  src/Pages/Login/MemberForm.scss
  src/config.js
  src/hello.js
Labels: Status: 수정 요청

#4 [손수민] Add: 메뉴 소개 컴포넌트 구현
  public/Images/ico_zzim2.png
  public/allMenu.json
  public/data/menu1.json
  public/data/menu2.json
  public/data/menu3.json
  public/data/menu4.json
  src/Components/TitleSection/TitleSection.js
  src/Components/TitleSection/TitleSection.scss
  src/Pages/Main/Banner/Banner.js
  src/Pages/Menu/Goods.js
  src/Pages/Menu/GoodsList.js
  src/Pages/Menu/Menu.js
  src/Pages/Menu/Menu.scss
  src/Pages/Menu/MenuFooter.js
  src/Pages/Menu/MenuFooter.scss
  src/Pages/Menu/MeunDetail/MenuDetail.scss
  src/Pages/Menu/MeunDetail/MeunDetail.js
  src/Pages/Menu/MeunDetail/MeunDetail.scss
  src/Routes.js
  src/Styles/common.scss
  src/configBasket.js
  src/configMenu.js
  src/index.js
Labels: Status: 도움 요청, Status: 리뷰 요청

#8 [손수민] Add: 장바구니 레이아웃 및 기능 구현
  package-lock.json
  package.json
  public/Images/bg_order_top.jpg
  public/Images/ico_x.png
  public/data/Basket.json
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Basket.scss
  src/Pages/Basket/BasketFeeds/BasketFeeds.js
  src/Pages/Basket/BasketFeeds/BasketFeeds.scss
  src/Routes.js
  src/configBasket.js
Labels: Status: 도움 요청, Status: 리뷰 요청, Status: 추가 기능 구현중

#5 [조윤민] Add: 상세페이지 레이아웃 구현
  package-lock.json
  public/Images/heart_icon.png
  public/Images/ingre1.png
  public/Images/ingre2.png
  public/Images/ingre3.png
  public/Images/menu.png
  public/Images/menu_subimage.png
  public/Images/pop_origin.jpg
  public/Images/product_detail.png
  public/Images/recommend1.png
  public/Images/recommend2.png
  public/Images/recommend3.png
  public/Images/share_icon.png
  public/Images/user_mypage.png
  public/Images/x_icon.png
  public/MockData/data.json
  src/Pages/Menu/MenuDetail/MenuDetail.js
  src/Pages/Menu/MenuDetail/MenuDetail.scss
  src/Pages/Menu/MenuDetail/components/DetailCard.js
  src/Pages/Menu/MenuDetail/components/DetailCard.scss
  src/Pages/Menu/MenuDetail/components/DetailList.js
  src/Pages/Menu/MenuDetail/components/DetailList.scss
  src/Pages/Menu/MenuDetail/components/IngredientCard.js
  src/Pages/Menu/MenuDetail/components/IngredientCard.scss
  src/Pages/Menu/MenuDetail/components/IngredientList.js
  src/Pages/Menu/MenuDetail/components/IngredientList.scss
  src/Pages/Menu/MenuDetail/components/Introduction.js
  src/Pages/Menu/MenuDetail/components/Introduction.scss
  src/Pages/Menu/MenuDetail/components/Origin.js
  src/Pages/Menu/MenuDetail/components/Origin.scss
  src/Pages/Menu/MenuDetail/components/Recommend.js
  src/Pages/Menu/MenuDetail/components/Recommend.scss
  src/Pages/Menu/MenuFooter.scss
  src/Pages/MyPage/MyPage.js
Labels: Status: 수정 요청

#10 [손수민] Modify: 메뉴 페이지 추가 구현
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Basket.scss
  src/Pages/Basket/BasketFeeds/BasketFeeds.js
  src/Pages/Basket/BasketFeeds/BasketFeeds.scss
  src/Pages/Login/Login.js
  src/Pages/Menu/Goods.js
  src/config.js
  src/configBasket.js
  src/configMenu.js
Labels: Status: 리뷰 요청

#12 [손수민] Modify: Basket에 공통 컴포넌트 추가
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Basket.scss
  src/Pages/Basket/BasketFeeds/BasketFeeds.js
  src/Pages/Basket/BasketFeeds/BasketFeeds.scss
  src/Pages/Menu/Goods.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
